---
title: "final_project"
author: "Kunxuan Wang"
date: "June 23, 2016"
output: html_document
---

```{r import-libraries}
library(raster)
library(rhdf5)
library(rgdal)
library(neonAOP)
library(ggplot2)
library(dplyr)
source("scripts/extract_h_plots.R")
source("scripts/process_raw_data.R")

```

```{r extract-plot-data}

# tag for if statement
# if TRUE, loops over all plots and saves average spectra
# if FALSE, extracts hyperspectral clip from first plot
EXTRACT_ALL <- TRUE

chm <- raster("../NEONdata/D03-Florida/OSBS/2014/lidar/OSBS_lidarCHM.tif")

# Need to set drive path
drivePath <- "D:/"
ground_height = 2 #max height in (m) of gound return
# get usable bands
good_bands_filename <- "supplemental_data/neon_aop_bands.csv"


epsg <- 32617 # set manually

# extract plot data
# plot_clip <- readOGR("../NEONdata/D03-Florida/OSBS/vector_data","ordway-crop-20140507-150703")
plt_centroids <- readOGR("../NEONdata/D03-Florida/OSBS/vector_data", "OSBS_PlotCentroids")
# plot(plt_centroids, add=TRUE)


# make record of plt results
# extract one plot centroid
plt_summary <- data.frame(plt_centroids$plotID)
plt_summary$center_E <- plt_centroids$easting
plt_summary$center_N <- plt_centroids$northing

plt_side_rad <- sqrt(plt_centroids$plotSize[1])/2   #half of plot side length

# split - run and extract all or run on first plot
if(EXTRACT_ALL == TRUE){
  
  # run for loop
  print("extracting all plot data, saving average spectra")
  
  # initiate object to store average spectra
  # NOTE: hard coding number of rows, can improve to make more flexible
  
  refl_plt_mean <- matrix(NA,ncol=369,nrow=length(plt_summary$center_E))
  volume <- matrix(NA,ncol=2,nrow=length(plt_summary$center_E))
  
  # NOTE: set to run on first 5 plots
  for (plt_num in 1:1) {
  #for (plt_num in 1:length(plt_summary$center_E)) {
    
    # extract plot extent
    plt_ext <- get_plot_extent(plt_summary$center_E[plt_num],
                               plt_summary$center_N[plt_num],
                               plt_side_rad)

    # get best? intersecting h5 file -> just one
    f <- get_best_h5_filename(plt_ext, drivePath)

    # extract processed hyper stack
    bands <- get_good_bands(good_bands_filename)
    
    # this line takes a few minutes to run
    all_h_data <- extract_hyper_stack(f, plt_ext, chm, ground_height, bands)

    # plot to check
    #plotRGB(all_h_data, 19, 34, 58, stretch="lin")

    # calculate average across all pixles within plot subset
    
    refl_plt_mean[plt_num,] <- average_plot_spectra(all_h_data, bands)[,2]
    
    # Perform the PCA
    a=rasterPCA(all_h_data, nComp = 3, nSamples = 1600, maskCheck=FALSE, norm = TRUE, spca = TRUE)
    vals <- a$map@data@values
    # Calculate the hypervolume
    hypervol = hypervolume(vals,bandwidth=estimate_bandwidth(vals,method="silverman"))
    
    tmpvol <- c(plt_num,hypervol@Volume)
    volume[plt_num,] <- tmpvol
    
    print(paste("extracting plot #",plt_num))
    
  }
  
  colnames(refl_plt_mean) <- all_h_data@data@names
  colnames(volume) <- c("plotid","Hypervolume")
  
  print("done extracting spectra for all plots")
    } else {
      
      # run first scene
      print("extracting spectra for first plot")
      
      plt_num = 1

      # extract plot extent
      plt_ext <- get_plot_extent(plt_summary$center_E[plt_num],
                                 plt_summary$center_N[plt_num],
                                 plt_side_rad)

      # get best? intersecting h5 file -> just one
      f <- get_h5_filename(plt_ext, drivePath)

      # extract processed hyper stack
      bands <- get_good_bands(good_bands_filename)

      all_h_data <- extract_hyper_stack(f, plt_ext, chm, ground_height, bands)

      # plot to check
      plotRGB(all_h_data, 19, 34, 58, stretch="lin")
      
      }

```

```{r average-all-spectra}
spectra <- average_plot_spectra(all_h_data, bands)

# plot spectra
qplot(x=spectra$wavelength,
      y=spectra$spectra,
      xlab="Wavelength (nm)",
      ylab="Reflectance",
      main="Spectra for all pixels")
      #ylim = c(0, .35))

```

